export default {
  mining: '⛏️',
  harvesting: '⛏️',
  picking: '⛏️',
  withdrawing: '📥',
  waiting: '⏳',
  transferring: '🔄',
  receiving: '📥',
  moving: '🚶',
  following: '👀',
  idle: '💤',
  full: '🛑',
  building: '🚧',
  upgrading: '⚡',
  repairing: '🔧',
  attacking: '💥',
  healing: '🩷',
};
